### PR TITLE
Try unpinning umap-learn

### PR DESCRIPTION
**Pull request by pinin4fjords**
Addressing https://github.com/ebi-gene-expression-group/scanpy-scripts/issues/102

### CODE REVIEW

**Comment by pinin4fjords** [comment]
currently a failure to do with mnnpy

**Comment by pinin4fjords** [comment]
This seems to be fine for 3.7 and 3.8 so should be done. FYI @LustigePerson, 3.9 seemed a bit patchy due to an issue with mnnpy in the python build process, but it may be okay at the conda level.

**Review by pcm32 — APPROVED** [review]
LGTM

**Comment by pinin4fjords** [comment]
Thanks @pcm32

**Comment by pinin4fjords** [comment]
Note: we need to intercept this at the Bioconda level too once I release.

**Pull request merged**
