### PR TITLE
Add loom support to v0.0.5

### PR DESCRIPTION
**Pull request by nh3**
This PR adds loom support for scanpy-scripts on top of release v0.0.5.
It defines an "exchangeable loom" format that extends Loom spec 2.0.1 based on the proposed Loom
3.0 feature (https://github.com/linnarsson-lab/loompy/issues/51), and provides functions for reading/storing all (except marker table) extra information that is currently not supported by scanpy's read/write_loom() function. The format is backward-compatible, meaning that the files generated can be read properly by scanpy (without the extra info that it can't read anyway) and LoomExperiment, and hopefully future proof by conforming to proposed Loom spec v3.0.

### CODE REVIEW

**Comment by pcm32** [comment]
Is this WIP still or should we review and merge?

**Comment by nh3** [comment]
I think it's ready for review and merge.

**Comment by nh3** [comment]
Hopefully this is ok?

**Comment by pcm32** [comment]
Sounds great!

**Pull request merged**
