### PR TITLE
Feature/function improvements

### PR DESCRIPTION
**Pull request by nh3**
This PR adds trajectory-related functions sc.tl.paga(), sc.tl.diffmap(), sc.tl.dpt(), scatter plot function, and includes a set of bugfix and improvements of existing functions.

### CODE REVIEW

**Comment by nh3** [comment]
They cover trajectory-related functions, but not scatter plots. I'm still a bit undecided whether to integrate plotting to calculation at the scripts level or at the galaxy wrapper level. The former is more flexible but the latter may save one IO.

**Comment by pcm32** [comment]
This looks good for me to merge at the moment. I would keep certain plotting facilities, turnable on and off, within the script. It is nice for users in Galaxy I think.

**Comment by pcm32** [comment]
Please merge at earliest convenience.

**Comment by nh3** [comment]
I've added plotting as a separate command (with tests included) for now. Will implement the other strategy in another PR.

**Pull request merged**
