### PR TITLE
Add mtx export to other matrix-altering scripts

### PR DESCRIPTION
**Pull request by pinin4fjords**
This PR adds the mtx output @nh3 added to the normalisation step to other matrix-altering Scanpy steps. 

@nh3 - I need to use a '-e' short argument for scale-data, since -x was in use.

### CODE REVIEW

**Comment by nh3** [comment]
Thanks @pinin4fjords. It's a pity that '-x' is not available in one of the scripts. This will be addressed in v0.2.x as options will be managed centrally and conflicts will be spotted early.

**Comment by pinin4fjords** [comment]
Sounds good @nh3 - have added the tweak to reflect modified export function

**Comment by pinin4fjords** [comment]
Any idea why the CI is failing here @nh3 ? It's not wanting to import output_mtx, but I can't see why

**Comment by nh3** [comment]
Perhaps because the name of the function is `export_mtx`?

**Comment by pinin4fjords** [comment]
Oh dear, facepalm moment- thanks!

**Comment by nh3** [comment]
I just noticed that as well, typos are among the hardest to spot...

**Comment by pinin4fjords** [comment]
Okay, thanks @nh3 , if you're happy, I will merge

**Comment by nh3** [comment]
Yep, go ahead. Thanks for the PR.

**Pull request merged**
