### PR TITLE
Feature/dotplots

### PR DESCRIPTION
**Pull request by pinin4fjords**
(Note: I'll change base branch to develop once https://github.com/ebi-gene-expression-group/scanpy-scripts/pull/62 is merged).

This PR adds dot plotting functionality, but also makes some associated changes:

- 'title' and 'frameon' removed as compulsory arguments for the dynamically generated plotting function. The violin plots just ignore these parameters, but supplying them for dot plotting causes an error. These parameters are now in a new optional set of plotting parameters.
- parameters common to differential expression plotting now have common set, factored out of the one initially created for violin plots.

### CODE REVIEW

**Comment by nh3** [comment]
I see you've been re-organising `COMMON_OPTIONS` to reduce duplication, which is good. Would be better if the names of those option groups are more informative, e.g. "plot_opt" -> "frame_title", and the link between "differential_pos" and "--var-names" is not obvious, for duplicated single option I tend not to put it in a list and just name it with the option name, but you are free to have your own design as long as readability is there. Not in this case but sometimes the same option can have different help messages, in which case I would keep them separate. In general, if you are to add more plotting functions in a short time, I suggest collating all the options and design the structure first.

**Comment by nh3** [comment]
Another consideration is to merge similar scanpy plotting functions into a wrapper function, with an option like "--kind" or "--style" to distinguish them. This way the wrapper function can absorb all options but only pass relevant options to the worker function and it can prevent having too many sub-sub-commands. But it's more of an opinion on design rather than implementation.

**Comment by pinin4fjords** [comment]
(now rebased to the updated develop branch)

Thanks @nh3 - the groupings made sense to me at the time (differential_pos = positional arguments for differential), but I see your points and renamed accordingly.

I did start thinking along the 'kind' lines, but it got a bit messy with the conditionals. In the end, just passing the arguments as optional parameters seemed to make sense. I'm less of a planner than you perhaps- but point taken.

More reorganisation in the next PR!

**Comment by pinin4fjords** [comment]
Great- thanks @nh3 - done!

**Pull request merged**
