### PR TITLE
Feature/stacked violins

### PR DESCRIPTION
**Pull request by pinin4fjords**
This PR adds a new 'stacked_violin' sub-function for the plot sub-command and an associated test, to be used in the upcoming training as requested by Pablo. The plot looks like:

[leiden_k10_r0_3_LDHB_CD3D_CD3E.pdf](https://github.com/ebi-gene-expression-group/scanpy-scripts/files/3841300/leiden_k10_r0_3_LDHB_CD3D_CD3E.pdf)

I've also had to add 'eval' to the commands in the .bats script. I was finding that the various _opt variables weren't being properly interpreted otherwise and the tests weren't running. If you've encountered that and solved it differently @nh3 do let me know.

Now I understand how to do this, I'll add more plotting in due course, incorporating any adjustments to the approach that Ni would like to suggest.

### CODE REVIEW

**Comment by nh3** [comment]
Looks great! A very minor complain: 'stacked_violin' is a lot to type on the command line. Could you change the sub-sub-command name to something shorter please? Maximum 8 characters, ideally under 6, considering one has to type 'plot' before it).

**Comment by pinin4fjords** [comment]
Thanks @nh3 - done!

**Comment by pinin4fjords** [comment]
@pcm32 - the missing functionality here is the 'var_group_positions' bit you'll see at https://icb-scanpy-tutorials.readthedocs-hosted.com/en/latest/visualizing-marker-genes.html, used to highlight particular parts of the plot. I decided that passing the tuples was too fiddly right now (I think I'd have to write a class @nh3 ?) and it would be better to work on other plots. But let me know if that's a priority.

**Comment by nh3** [comment]
> @pcm32 - the missing functionality here is the 'var_group_positions' bit you'll see at https://icb-scanpy-tutorials.readthedocs-hosted.com/en/latest/visualizing-marker-genes.html, used to highlight particular parts of the plot. I decided that passing the tuples was too fiddly right now (I think I'd have to write a class @nh3 ?) and it would be better to work on other plots. But let me know if that's a priority.

Yes, a custom class is the ideal solution, but those options are not that important to me. If one really wants, a potential ready-to-use solution is to combine var_group_positions and var_group_labels into one option and re-use the Dictionary class already implemented, asking users to provide `<labelA>:<idxA1-idxA2>,<labelB>:<idxB1-idxB2>,...`, of course that doesn't check everything and a little parsing is still required to separate idxA1 and idxA2.

**Comment by pinin4fjords** [comment]
Apologies- have added rank_genes_groups_stacked_violin() to this branch- maybe you want to check it over once more? It's a wrapper of stacked_violin() producing a plot like:

[rggsviolin_leiden_k10_r0_3_LDHB_CD3D_CD3E.pdf](https://github.com/ebi-gene-expression-group/scanpy-scripts/files/3841811/rggsviolin_leiden_k10_r0_3_LDHB_CD3D_CD3E.pdf)

I was going to make a separate PR, but actually I needed to re-factor the arguments so it's probably best reviewed here. The new function got long to differentiate it from the previous- so I shrunk both.

**Comment by pinin4fjords** [comment]
Thanks @nh3 !

**Pull request merged**
