### PR TITLE
[WIP] Proposal to move certain observations generation to read step

### PR DESCRIPTION
**Pull request by pcm32**
Currently to be able to use 'n_counts', 'n_genes', etc and so on, one needs to go through the filtering step. I think it would make more sense, specially to be able to do QC right after reading, to enable the same parts that generate those observations in the filtering step to be present in the reading step (not sure where you are putting the common code calls @nh3 to avoid duplication, but it you let me know, I can put the repeated code there).

I intend to add as well to the read step an option for the prefix of the spikes, so that and percentage obs can be calculated as well for those. Those things would complete the functionality for Chichau's QC part for the course (besides some plots we would need to add).

### CODE REVIEW

**Comment by pcm32** [comment]
My other question is whether at the read method we have certainty of the var where the gene names are, or could the h5 10x flavour introduce noise here? Or will it always be 'index'? Thanks!

**Comment by nh3** [comment]
If var_names="gene_symbols", then index will be 1st column (gene symbols) of genes.tsv.
If var_names="gene_ids", then index will be 2nd column (gene IDs) of genes.tsv, and gene symbols will be in a column named "gene_symbols".

**Comment by pcm32** [comment]
I thought that Gene IDs would be in the first column and gene symbols in the second column (of the gene.tsv file), at least that is how we are producing them on the downloader tool.

**Comment by pcm32** [comment]
Did this order change recently? Maybe that explain some CellBrowser examples I got where I was back with gene identifiers instead of gene symbols?

**Comment by pcm32** [comment]
Should we add a flag that indicates whether these QCs should be calculated or not?

**Comment by pcm32** [comment]
Ok, I realise that what I'm adding here is not elegant, but we would need something like this to have the mito and ERCC % counts calculated straightaway for the course. Could you be able to bridge my addition here @nh3 with what is needed so that the `gene_startswith` argument gets passed to the _read? Then I can ammend the Galaxy module. This, plus using the plot module from Freiburg will allow us to get off the first part of QC.

**Comment by nh3** [comment]
> I thought that Gene IDs would be in the first column and gene symbols in the second column (of the gene.tsv file), at least that is how we are producing them on the downloader tool.

Yes, you are right. It should be:

If var_names="gene_symbols", then index will be 2nd column (gene symbols) of genes.tsv.
If var_names="gene_ids", then index will be 1st column (gene IDs) of genes.tsv, and gene symbols will be in a column named "gene_symbols".

**Comment by nh3** [comment]
I don't fully understand what SCCAF requires, but if it's run at the Galaxy level, then the simplest approach is to just run "scanpy-cli filter -p c:pct_counts_mito 0 100 -p c:pct_counts_ERCC 0 100 <input.h5> <output.h5>" in the read_10x step. This way, nothing is filtered but all the metric you need are calculated.

**Comment by pinin4fjords** [comment]
@pablo, remember I improved that GTF tool to create mito annotations in format that Scanpy could digest, and in a more reliable manner

**Comment by nh3** [comment]
> @pablo, remember I improved that GTF tool to create mito annotations in format that Scanpy could digest, and in a more reliable manner

If a boolean field can be inserted into the gene metadata table in a similar fashion as mito, then scanpy-cli filter is able to generate QC metrics (pct_counts_ERCC) on that too.

**Comment by pcm32** [comment]
I think I'll pursue an avenue outside of read 10x. I understand that with certain work arounds ss suggested we can achieve what we are after, but I want to be more explicit and accommodate what the trainer is after for the course. I've written similar logic on a PR I'll make to the container repo, afterwards that cash be left there or incorporated to another module. Thanks guys!

**Comment by nh3** [comment]
One could add a "calculate_QC_metric" galaxy step that actually calls "scanpy-cli filter" with parameters that doesn't filter anything but simply calculate metrics...

**Pull request closed without merging**
