### PR TITLE
Add export_mtx() to v0.0.4

### PR DESCRIPTION
**Pull request by nh3**
This PR adds a function to export mtx from anndata, and use it to optionally export normalised data.

### CODE REVIEW

**Comment by pinin4fjords** [comment]
Hi Ni - can we add the export option to the other stages as well?

**Comment by pinin4fjords** [comment]
Most tools expect the specific file names matrix.mtx, genes.tsv and barcodes.tsv- should we not keep to that convention? I realise that's not how Nuno set things up for Atlas, but I think that was probably the wrong choice.

**Comment by pinin4fjords** [comment]
I realise that would have problems outputing multiple mtx files to the same directory- hence the archive solution I suggested

**Comment by pinin4fjords** [comment]
... but maybe the right solution is just to allow no prefix?

**Comment by nh3** [comment]
Thanks @pinin4fjords. I'd like to keep flexibility to write outputs to arbitrary locations and names. So the prefix is kept but its processing is modified a little to allow the naming you requested.

**Comment by pinin4fjords** [comment]
Brilliant- good solution @nh3

**Pull request merged**
